import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "@/components/UiIcons";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { ScrollReveal } from "@/components/ScrollReveal";

export const metadata: Metadata = { title: "Global Markets", description: "Begin a fragrance development conversation for your target market and application.", alternates: { canonical: "/markets" } };
export default function MarketsPage() { return <main id="main-content"><SiteHeader /><section className="listing-hero"><p className="eyebrow">GLOBAL MARKETS</p><h1>Designed for conversations that cross borders.</h1><p className="lead">Tell us your intended market early so the project discussion can begin with the context that matters.</p></section><ScrollReveal className="market-story section"><Image src="/images/global-market-map.png" alt="Stylized dotted global map" width={1600} height={900} /><div><h2>Application, market, sample, next step.</h2><p>Every market and product route has a different set of questions. Our inquiry structure makes space for the details that help a project move forward.</p><Link className="text-link" href="/request-a-quote">Tell us about your market <ArrowRight size={17} /></Link></div></ScrollReveal><ScrollReveal className="event-gallery section"><div className="section-heading"><h2>Conversations that continue beyond the screen.</h2><p>Our event photography provides a direct view of how Sai Zhao presents its fragrance work in person.</p></div><div className="event-gallery-grid"><figure className="event-feature"><Image src="/images/facility/trade-show-01.jpg" alt="Sai Zhao exhibition booth at an industry event" fill sizes="(max-width: 800px) 100vw, 55vw" className="cover-image" /></figure><figure><Image src="/images/facility/trade-show-02.jpg" alt="Sai Zhao exhibition stand" fill sizes="(max-width: 800px) 100vw, 30vw" className="cover-image" /></figure><figure><Image src="/images/facility/trade-show-03.jpg" alt="Sai Zhao team meeting visitors at a trade show" fill sizes="(max-width: 800px) 100vw, 30vw" className="cover-image" /></figure></div></ScrollReveal><ScrollReveal className="feature-band"><div><h3>Target market</h3><p>Where will the product be introduced?</p></div><div><h3>Product route</h3><p>What kind of finished product is being developed?</p></div><div><h3>Project timing</h3><p>What does the sample and launch schedule need to support?</p></div></ScrollReveal><SiteFooter /></main>; }
