import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Factory, GlobeHemisphereWest, MapPin, Phone } from "@/components/UiIcons";
import { PageHero } from "@/components/PageHero";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { company } from "@/lib/site-data";

export const metadata: Metadata = { title: "Contact", description: "Start a conversation with Zhejiang Sai Zhao Flavor And Fragrance Co., Ltd.", alternates: { canonical: "/contact" } };
export default function ContactPage() { return <main id="main-content"><SiteHeader /><PageHero eyebrow="CONTACT" title="Start with the conversation your product needs." intro="Tell us what you are developing and we will guide the inquiry toward the right next step." image="/images/sai-zhao-factory-gate.jpg" imageAlt="Entrance to the Sai Zhao factory" /><section className="contact-details section"><article><Phone size={30} weight="light" /><h2>{company.contactName}</h2><a className="contact-phone" href={company.telephoneHref}>{company.telephone}</a><p>Call to begin a project, factory or sample discussion.</p></article><article><MapPin size={30} weight="light" /><h2>Jiangshan, Zhejiang</h2><address>{company.address}</address></article><article><Factory size={30} weight="light" /><h2>Share the essentials.</h2><p>Use the structured brief to share product, application, market and desired timing.</p><Link className="text-link" href="/request-a-quote">Share Your Brief <ArrowRight size={17} /></Link></article></section><section className="contact-grid section"><article><Factory size={30} weight="light" /><h2>Factory conversation</h2><p>For a facility or production discussion, begin with the product route and desired timing.</p><Link className="text-link" href="/request-a-quote">Start an inquiry <ArrowRight size={17} /></Link></article><article><GlobeHemisphereWest size={30} weight="light" /><h2>Market context</h2><p>Share where the product will be introduced so the project can start with the relevant questions.</p><Link className="text-link" href="/markets">Explore markets <ArrowRight size={17} /></Link></article></section><SiteFooter /></main>; }
