import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle } from "@/components/UiIcons";
import { PageHero } from "@/components/PageHero";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "About Sai Zhao Fragrance", description: "Learn about Zhejiang Sai Zhao Flavor And Fragrance Co., Ltd." };
export default function AboutPage() { return <main><SiteHeader /><PageHero eyebrow="ABOUT SAI ZHAO" title="A fragrance partner built for product makers." intro="Zhejiang Sai Zhao Flavor And Fragrance Co., Ltd. brings product, fragrance direction and manufacturing conversation into one clearer route." image="/images/facility/factory-campus.png" /><section className="content-section two-column"><div><p className="eyebrow">OUR APPROACH</p><h2>Listen first. Develop with intention.</h2></div><div><p>We work from the product brief outward: what is being made, who it is for, where it will be used and what the scent should help it become.</p><p>That approach keeps communication practical—from an initial direction through sampling and the next production discussion.</p><Link className="text-link" href="/request-a-quote">Share your project <ArrowRight size={17} /></Link></div></section><section className="feature-band"><div><CheckCircle size={26} weight="light" /><h3>Application-first</h3><p>Start with the real product context, not a generic fragrance list.</p></div><div><CheckCircle size={26} weight="light" /><h3>Factory-connected</h3><p>Keep development and manufacturing conversation close together.</p></div><div><CheckCircle size={26} weight="light" /><h3>Built for dialogue</h3><p>Use samples and feedback to establish the next step.</p></div></section><section className="facility-gallery section"><div className="section-heading"><p className="eyebrow">INSIDE SAI ZHAO</p><h2>Space for development, coordination and production.</h2></div><div className="facility-gallery-grid"><figure className="gallery-wide"><Image src="/images/facility/office-panorama.jpg" alt="Sai Zhao office environment" fill sizes="(max-width: 800px) 100vw, 65vw" className="cover-image" /><figcaption>Office &amp; project coordination</figcaption></figure><figure><Image src="/images/facility/factory-panorama.jpg" alt="Sai Zhao factory campus overview" fill sizes="(max-width: 800px) 100vw, 40vw" className="cover-image" /><figcaption>Factory campus</figcaption></figure><figure><Image src="/images/facility/workshop-panorama.jpg" alt="Sai Zhao workshop environment" fill sizes="(max-width: 800px) 100vw, 40vw" className="cover-image" /><figcaption>Production environment</figcaption></figure></div></section><SiteFooter /></main>; }
