import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle } from "@phosphor-icons/react";
import { PageHero } from "@/components/PageHero";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "About Sai Zhao Fragrance", description: "Learn about Zhejiang Sai Zhao Flavor And Fragrance Co., Ltd." };
export default function AboutPage() { return <main><SiteHeader /><PageHero eyebrow="ABOUT SAI ZHAO" title="A fragrance partner built for product makers." intro="Zhejiang Sai Zhao Flavor And Fragrance Co., Ltd. brings product, fragrance direction and manufacturing conversation into one clearer route." image="/images/sai-zhao-factory-gate.png" /><section className="content-section two-column"><div><p className="eyebrow">OUR APPROACH</p><h2>Listen first. Develop with intention.</h2></div><div><p>We work from the product brief outward: what is being made, who it is for, where it will be used and what the scent should help it become.</p><p>That approach keeps communication practical—from an initial direction through sampling and the next production discussion.</p><Link className="text-link" href="/request-a-quote">Share your project <ArrowRight size={17} /></Link></div></section><section className="feature-band"><div><CheckCircle size={26} weight="light" /><h3>Application-first</h3><p>Start with the real product context, not a generic fragrance list.</p></div><div><CheckCircle size={26} weight="light" /><h3>Factory-connected</h3><p>Keep development and manufacturing conversation close together.</p></div><div><CheckCircle size={26} weight="light" /><h3>Built for dialogue</h3><p>Use samples and feedback to establish the next step.</p></div></section><SiteFooter /></main>; }
