"use client";
import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { readCart, writeCart, type CartLine } from "@/lib/retail-cart";
import { formatMoney } from "@/lib/retail-types";

type Quote = { lines: { variantId: string; title: string; slug: string; label: string; image: string | null; quantity: number; unitPriceMinor: number; lineTotalMinor: number; available: number }[]; subtotalMinor: number; shippingMinor: number | null; taxMinor: number | null; totalMinor: number | null; zone: { country_name: string } | null; checkoutEnabled: boolean };
export function CartView({ checkout = false }: { checkout?: boolean }) {
  const [lines, setLines] = useState<CartLine[]>([]); const [quote, setQuote] = useState<Quote | null>(null); const [message, setMessage] = useState(""); const [country, setCountry] = useState(""); const [countries, setCountries] = useState<{ country_code: string; country_name: string }[]>([]);
  useEffect(() => { const timer = window.setTimeout(() => setLines(readCart()), 0); fetch("/api/shop/countries").then((r) => r.json()).then((v) => setCountries(v.data || [])).catch(() => undefined); return () => window.clearTimeout(timer); }, []);
  useEffect(() => {
    if (!lines.length) return;
    const controller = new AbortController();
    fetch("/api/shop/quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: lines.map((l) => ({ variantId: l.variantId, quantity: l.quantity })), country }), signal: controller.signal }).then(async (r) => { const v = await r.json(); if (!r.ok) throw new Error(v.message); setQuote(v); setMessage(""); }).catch((error) => { if (error.name !== "AbortError") { setQuote(null); setMessage(error.message); } });
    return () => controller.abort();
  }, [lines, country]);
  function change(id: string, quantity: number) { const next = lines.map((l) => l.variantId === id ? { ...l, quantity } : l).filter((l) => l.quantity > 0); setQuote(null); setLines(next); writeCart(next); }
  return <div className="retail-cart-layout"><div><h1>{checkout ? "Checkout" : "Your Cart"}</h1>{!lines.length ? <div className="retail-cart-empty"><p>Your cart is empty.</p><Link className="retail-solid" href="/products">Explore products</Link></div> : <div className="retail-cart-items">{lines.map((line) => { const fresh = quote?.lines.find((x) => x.variantId === line.variantId); return <article key={line.variantId}><div className="retail-cart-image">{line.image && <Image src={line.image} alt={line.title} fill sizes="90px" />}</div><div><Link href={`/products/${line.slug}`}><strong>{fresh?.title || line.title}</strong></Link><p>{fresh?.label || line.label}</p><button type="button" onClick={() => change(line.variantId, 0)}>Remove</button></div><div className="retail-cart-controls"><label>Qty <input aria-label={`Quantity for ${line.title}`} type="number" min="1" max="20" value={line.quantity} onChange={(e) => change(line.variantId, Math.min(20, Math.max(1, Number(e.target.value) || 1)))} /></label><strong>{fresh ? formatMoney(fresh.lineTotalMinor) : "—"}</strong>{fresh && fresh.available < line.quantity && <small>Insufficient stock</small>}</div></article>; })}</div>}{message && <p role="alert">{message}</p>}</div><aside className="retail-cart-summary"><h2>Order Summary</h2><label>Delivery country<select value={country} onChange={(e) => setCountry(e.target.value)}><option value="">Select your country</option>{countries.map((c) => <option value={c.country_code} key={c.country_code}>{c.country_name}</option>)}</select></label><dl><div><dt>Subtotal</dt><dd>{quote ? formatMoney(quote.subtotalMinor) : "—"}</dd></div><div><dt>Shipping</dt><dd>{quote?.shippingMinor !== null && quote?.shippingMinor !== undefined ? formatMoney(quote.shippingMinor) : "Select country"}</dd></div><div><dt>Estimated tax</dt><dd>{quote?.taxMinor !== null && quote?.taxMinor !== undefined ? formatMoney(quote.taxMinor) : "—"}</dd></div><div className="retail-cart-total"><dt>Total</dt><dd>{quote?.totalMinor !== null && quote?.totalMinor !== undefined ? formatMoney(quote.totalMinor) : "—"}</dd></div></dl>{!checkout && <Link className="retail-solid" href="/checkout">Continue to checkout</Link>}{checkout && <CheckoutForm country={country} lines={lines} quote={quote}/>}</aside></div>;
}
function CheckoutForm({ country, lines, quote }: { country: string; lines: CartLine[]; quote: Quote | null }) {
  const [buyer, setBuyer] = useState({ name: "", email: "", phone: "", address1: "", address2: "", city: "", region: "", postalCode: "" });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const ready = Boolean(quote?.checkoutEnabled && quote.zone && quote.totalMinor !== null && lines.length && quote.lines.every((line) => line.available >= line.quantity));
  async function submit(event: FormEvent) {
    event.preventDefault(); if (!ready) return; setBusy(true); setMessage("");
    try {
      const response = await fetch("/api/shop/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ country, buyer, items: lines.map((line) => ({ variantId: line.variantId, quantity: line.quantity })) }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.message || "Unable to start payment");
      if (typeof result.approvalUrl !== "string" || !result.approvalUrl.startsWith("https://")) throw new Error("Invalid payment response");
      window.location.assign(result.approvalUrl);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to start payment"); setBusy(false); }
  }
  return <><h3>Delivery details</h3>{!quote?.checkoutEnabled && <p className="retail-checkout-notice">Online payment is not yet open. Please contact our team to place an order.</p>}<form onSubmit={submit}><fieldset disabled={!ready || busy}><label>Full name<input required autoComplete="name" value={buyer.name} onChange={(e) => setBuyer({ ...buyer, name: e.target.value })} /></label><label>Email<input required type="email" autoComplete="email" value={buyer.email} onChange={(e) => setBuyer({ ...buyer, email: e.target.value })} /></label><label>Phone<input autoComplete="tel" value={buyer.phone} onChange={(e) => setBuyer({ ...buyer, phone: e.target.value })} /></label><label>Address line 1<input required autoComplete="address-line1" value={buyer.address1} onChange={(e) => setBuyer({ ...buyer, address1: e.target.value })} /></label><label>Address line 2<input autoComplete="address-line2" value={buyer.address2} onChange={(e) => setBuyer({ ...buyer, address2: e.target.value })} /></label><label>City<input required autoComplete="address-level2" value={buyer.city} onChange={(e) => setBuyer({ ...buyer, city: e.target.value })} /></label><label>State / region<input autoComplete="address-level1" value={buyer.region} onChange={(e) => setBuyer({ ...buyer, region: e.target.value })} /></label><label>Postal code<input required autoComplete="postal-code" value={buyer.postalCode} onChange={(e) => setBuyer({ ...buyer, postalCode: e.target.value })} /></label><button type="submit">{busy ? "Connecting to PayPal…" : "Pay securely with PayPal"}</button></fieldset></form>{message && <p role="alert">{message}</p>}<p><Link href="/request-a-quote">Need a custom order? Contact our team</Link></p></>;
}
