import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle, Clock, DownloadSimple, Flask, Globe, LockKey, Package, ShieldCheck, ShoppingCart, Sparkle, Thermometer, Truck } from "@phosphor-icons/react/dist/ssr";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { ProductPurchase } from "@/components/retail/ProductPurchase";
import { formatMoney, type RetailProduct } from "@/lib/retail-types";
import { checkoutReady } from "@/lib/paypal";
import "@/app/products/product-detail.css";

const sampleApplications = [
  { title: "Candles", description: "A warm, balanced fragrance experience", image: "/images/retail/candle.jpg", alt: "Fragranced candle" },
  { title: "Reed Diffusers", description: "Continuous ambient fragrance", image: "/images/retail/reed-diffuser.jpg", alt: "Reed diffuser" },
  { title: "Room Sprays", description: "A fresh, uplifting mist", image: "/images/retail/room-spray.jpg", alt: "Room spray bottle" },
];

export function ProductDetailView({ product, related = [], preview = false }: { product: RetailProduct; related?: RetailProduct[]; preview?: boolean }) {
  const detail = product.detail;
  const hero = product.hero_url || product.cover_url || "/images/retail/fresh-linen-hero.jpg";
  const applications = detail.applications.length ? detail.applications : product.is_demo ? sampleApplications : [];
  return <><SiteHeader /><main id="main-content" className="retail-page">
    {preview && <div className="retail-preview-banner">Admin preview · This draft is not visible to customers. <Link href="/admin/products">Manage products</Link></div>}
    <section className="retail-top">
      <div className="retail-hero-image"><Image src={hero} alt={product.gallery[0]?.alt || product.title} fill priority sizes="(max-width: 900px) 100vw, 56vw" /><div className="retail-hero-copy"><span>SAI ZHAO FRAGRANCE</span><h2>{detail.heroLine || "Fragrance Enriches Everyday Living"}</h2><p>{detail.heroDescription || "From concept to creation, we craft fragrances for a more beautiful world."}</p></div><div className="retail-hero-trust"><span><Sparkle size={22}/> Thoughtful Fragrance</span><span><Flask size={22}/> Application-Led Development</span><span><Package size={22}/> Global Supply</span></div></div>
      <div className="retail-summary"><nav aria-label="Breadcrumb"><Link href="/">Home</Link> › <Link href="/products">Products</Link> › {product.title}</nav>{product.badge && <span className="retail-badge">{product.badge}</span>}<h1>{product.title}</h1>{product.subtitle && <p className="retail-subtitle">{product.subtitle}</p>}<p className="retail-description">{product.summary}</p><ProductPurchase product={product} preview={preview} checkoutEnabled={checkoutReady()} /><div className="retail-assurances"><span><LockKey size={22}/> {checkoutReady() ? "Secure checkout" : "Order support"}</span><span><Globe size={22}/> Shipping by region</span><span><ShieldCheck size={22}/> Quality focused</span><span><Truck size={22}/> Delivery support</span></div></div>
    </section>
    {product.gallery.length > 1 && <div className="retail-gallery" aria-label="Product images">{product.gallery.slice(1, 5).map((image, index) => <div key={`${image.url}-${index}`}><Image src={image.url} alt={image.alt} fill sizes="(max-width: 700px) 45vw, 23vw" /></div>)}</div>}
    <section className="retail-overview retail-two-column"><div><h2>Product Overview</h2><p>{detail.overview || product.content}</p><div className="retail-icon-list"><span><Sparkle/> Crafted for Everyday Spaces</span><span><Flask/> Application Versatility</span><span><Clock/> Lasting Impression</span></div></div><div><h2>Technical Highlights</h2>{detail.technical.length ? <dl className="retail-table">{detail.technical.map((row, index) => <div key={`${row.label}-${index}`}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl> : <p>Technical details can be supplied on request.</p>}</div></section>
    <section className="retail-profile-grid"><div className="retail-panel"><h2>Fragrance Profile</h2><div className="retail-notes"><div className="retail-note-visual"><span>TOP</span><span>HEART</span><span>BASE</span></div><dl><div><dt>Top Notes</dt><dd>{detail.topNotes || "Contact us for fragrance notes"}</dd></div><div><dt>Heart Notes</dt><dd>{detail.heartNotes || "—"}</dd></div><div><dt>Base Notes</dt><dd>{detail.baseNotes || "—"}</dd></div></dl></div></div><div className="retail-panel"><h2>Performance in Applications</h2>{applications.length ? <div className="retail-application-grid">{applications.map((item, index) => <article key={`${item.title}-${index}`}><div><Image src={item.image} alt={item.alt} fill sizes="(max-width: 700px) 44vw, 15vw" /></div><h3>{item.title}</h3><p>{item.description}</p></article>)}</div> : <p>Recommended applications will be listed here.</p>}</div><div className="retail-panel"><h2>Dosage Guidance</h2><p>Recommended use level depends on application and formulation.</p>{detail.dosage.length ? <ul>{detail.dosage.map((row) => <li key={row.label}>{row.label}: {row.value}</li>)}</ul> : <p>Contact our team for guidance.</p>}<small>Final dosage should be validated in your finished product.</small></div></section>
    <section className="retail-logistics-grid"><div className="retail-panel"><h2>Packaging Sizes</h2><div className="retail-packaging-image"><Image src={detail.packagingImage || product.gallery[0]?.url || hero} alt={product.is_demo ? "Illustrative packaging range" : `${product.title} packaging`} fill sizes="(max-width: 700px) 100vw, 33vw" /></div><p>{detail.packagingIntro || "Packaging options may vary by product and order size."}</p></div><div className="retail-panel"><h2>Storage Advice</h2><ul className="retail-icon-bullets">{(detail.storage.length ? detail.storage : ["Store in a cool, dry place", "Avoid direct sunlight", "Keep container tightly closed"]).map((item) => <li key={item}><Thermometer size={20}/>{item}</li>)}</ul></div><div className="retail-panel"><h2>Shipping Information</h2><ul className="retail-icon-bullets">{(detail.shipping.length ? detail.shipping : ["Delivery options shown at checkout", "Secure packaging", "Tracking available when dispatched"]).map((item) => <li key={item}><Truck size={20}/>{item}</li>)}</ul></div></section>
    <section className="retail-paths"><article><ShoppingCart size={30}/><div><h2>Retail Purchase</h2><p>Choose an available size and complete a secure online order.</p><ul>{detail.retailBenefits.map((item) => <li key={item}><CheckCircle size={16}/>{item}</li>)}</ul><Link href="/cart">View Cart <ArrowRight size={16}/></Link></div></article><span className="retail-or">OR</span><article><Flask size={30}/><div><h2>Bulk / Custom Fragrance Project</h2><p>Tailored solutions for brands and application needs.</p><ul>{detail.customBenefits.map((item) => <li key={item}><CheckCircle size={16}/>{item}</li>)}</ul><Link href="/request-a-quote">Request a Custom Brief <ArrowRight size={16}/></Link></div></article></section>
    <section className="retail-brief-band"><div><h2>Request a Custom Brief</h2><p>Share your idea, application and quantity with our team.</p></div><Link href="/request-a-quote">Share Your Brief <ArrowRight size={17}/></Link></section>
    <section className="retail-process"><h2>Our Fragrance Development & Manufacturing Process</h2><div>{[["01", "Brief & Insight", "Understand your needs and intended application."], ["02", "Concept & Direction", "Develop a fragrance direction and sample plan."], ["03", "Sampling & Refinement", "Evaluate and fine-tune the formula."], ["04", "Scale & Delivery", "Manufacture and deliver the agreed product."]].map(([number, title, description]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>
    <section className="retail-docs-faq retail-two-column"><div><h2>Downloads</h2><p>Available product documents and technical information.</p><div className="retail-downloads">{detail.downloads.length ? detail.downloads.map((item) => <a key={item.url} href={item.url} target="_blank" rel="noreferrer"><span>{item.title}<small>{item.note}</small></span><DownloadSimple size={19}/></a>) : product.attachment_url ? <a href={product.attachment_url} target="_blank" rel="noreferrer"><span>Product information</span><DownloadSimple size={19}/></a> : <p>Documents are available on request.</p>}</div></div><div><h2>FAQ</h2><div className="retail-faq">{detail.faqs.length ? detail.faqs.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>) : <p>Have a question? <Link href="/request-a-quote">Contact our team.</Link></p>}</div></div></section>
    {related.length > 0 && <section className="retail-related"><h2>Related Products</h2><div>{related.map((item) => <Link href={`/products/${item.slug}`} key={item.id}><div>{(item.cover_url || item.hero_url) && <Image src={(item.cover_url || item.hero_url)!} alt={item.title} fill sizes="(max-width: 700px) 45vw, 20vw" />}</div><h3>{item.title}</h3><span>{item.variants[0] ? formatMoney(item.variants[0].price_minor, item.variants[0].currency) : "Explore product"}</span></Link>)}</div></section>}
  </main><SiteFooter /></>;
}
