import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, ArrowUpRight, CheckCircle, Flask, GlobeHemisphereWest, Sparkle } from "@/components/UiIcons";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { ScrollReveal } from "@/components/ScrollReveal";
import { applicationImageAlt, applications } from "@/lib/site-data";

export const metadata: Metadata = { alternates: { canonical: "/" } };

export default function Home() {
  return <main id="main-content">
    <section className="hero"><SiteHeader /><div className="hero-content"><div className="hero-copy"><p className="eyebrow">GLOBAL B2B FRAGRANCE MANUFACTURER</p><h1>Formulas<br />with feeling.</h1><p className="lead">We help brands move from product brief through scent direction, sampling, formula refinement and production communication.</p><Link className="button" href="/request-a-quote">Share Your Brief <ArrowUpRight size={18} /></Link><div className="proof-row"><span><Sparkle size={20} />Application-led<br />development</span><span><Flask size={20} />Sampling &amp;<br />refinement</span><span><CheckCircle size={20} />Production-connected<br />communication</span><span><GlobeHemisphereWest size={20} />International<br />project support</span></div></div><div className="hero-image-wrap"><Image src="/images/hero-fragrance-still-life.jpg" alt="Amber fragrance bottles, aromatic botanicals and citrus in a warm studio" fill preload sizes="(max-width: 800px) 100vw, 52vw" className="cover-image" /></div></div></section>
    <section className="applications section"><ScrollReveal className="section-intro"><h2>Scents that bring products to life.</h2><p>Explore a clear application-led route into custom fragrance development.</p><Link className="text-link" href="/applications">View all applications <ArrowRight size={17} /></Link></ScrollReveal><div className="application-grid">{applications.map(({ title, description, image, slug }, index) => <ScrollReveal key={slug} delay={index * 80}><article className="application-card"><Link href={`/applications/${slug}`}><Image src={image} alt={applicationImageAlt(title)} width={700} height={700} className="card-image" /></Link><div className="application-card-copy"><h3>{title}</h3><p>{description}</p><Link href={`/applications/${slug}`}>Explore application <ArrowRight size={15} /></Link></div></article></ScrollReveal>)}</div></section>
    <section className="process-section section"><div className="process-image"><Image src="/images/facility/workshop-panorama.jpg" alt="Sai Zhao workshop and production environment" fill sizes="(max-width: 800px) 100vw, 45vw" className="cover-image" /></div><div className="process-copy"><h2>Your vision.<br />Our expertise.</h2><p>From first inspiration to a production-ready formula, each stage keeps your application and brand direction in view.</p><ol className="process-list"><li><span>01</span><div><h3>Brief & Insight</h3><p>Share the application, market and desired scent direction.</p></div></li><li><span>02</span><div><h3>Concept & Direction</h3><p>Develop an initial direction around your brief.</p></div></li><li><span>03</span><div><h3>Sampling & Refinement</h3><p>Evaluate and adjust the concept together.</p></div></li><li><span>04</span><div><h3>Scale & Delivery</h3><p>Prepare the agreed formula for the next production step.</p></div></li></ol><Link className="text-link" href="/capabilities">Explore capabilities <ArrowRight size={17} /></Link></div></section>
    <section className="quality section"><div className="quality-copy"><h2>Built on quality.<br />Delivered with care.</h2><p>Quality starts with a clear brief, thoughtful formulation and a disciplined route from sample to supply.</p><ul><li><CheckCircle size={18} weight="fill" />Application-conscious development</li><li><CheckCircle size={18} weight="fill" />Sample refinement before scale-up</li><li><CheckCircle size={18} weight="fill" />Factory-led production communication</li></ul><Link className="text-link text-link-light" href="/quality">Explore our approach <ArrowRight size={17} /></Link></div><div className="quality-image"><Image src="/images/facility/workshop-control.jpg" alt="Sai Zhao production control area" fill sizes="(max-width: 800px) 100vw, 52vw" className="cover-image" /></div></section>
    <section className="company-showcase section"><ScrollReveal className="section-heading"><h2>Closer to the work.</h2></ScrollReveal><ScrollReveal className="company-showcase-grid"><Link className="showcase-card showcase-campus" href="/about"><Image src="/images/facility/factory-campus.jpg" alt="Sai Zhao factory campus" fill sizes="(max-width: 800px) 100vw, 55vw" className="cover-image" /><span>Factory campus <ArrowRight size={17} /></span></Link><div className="showcase-stack"><Link className="showcase-card" href="/capabilities"><Image src="/images/facility/office-panorama.jpg" alt="Sai Zhao office team environment" fill sizes="(max-width: 800px) 100vw, 32vw" className="cover-image" /><span>Project coordination <ArrowRight size={17} /></span></Link><Link className="showcase-card" href="/markets"><Image src="/images/facility/trade-show-03.jpg" alt="Sai Zhao at an industry trade show" fill sizes="(max-width: 800px) 100vw, 32vw" className="cover-image" /><span>Industry events <ArrowRight size={17} /></span></Link></div></ScrollReveal></section>
    <section className="markets section"><div className="markets-copy"><h2>A partner for brands building scent-led products.</h2><p>We structure each project around the application, desired market, sample process and next production step.</p><Link href="/markets" className="text-link">Explore markets <ArrowRight size={17} /></Link></div><div className="map-wrap"><Image src="/images/global-market-map.png" alt="Stylized global market map" width={1600} height={900} className="map-image" /></div><aside className="brief-card"><h2>Share your brief with our team.</h2><p>Tell us what you are creating. We will route your request to the right next step.</p><Link className="button" href="/request-a-quote">Start your brief <ArrowUpRight size={18} /></Link></aside></section>
    <SiteFooter />
  </main>;
}
