import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Plus } from "@phosphor-icons/react";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

export const metadata: Metadata = { title: "Frequently Asked Questions | Sai Zhao", description: "Common questions about starting a fragrance development project." };
const questions = [["What should I include in my first brief?", "The finished product, target market, desired scent direction, expected timing and any sample reference are the most useful starting points."], ["Can you support a custom fragrance direction?", "Yes. A custom project begins with the application and fragrance brief, then moves through sample discussion and refinement."], ["How should we approach sampling?", "Use the first sample to establish direction, then give specific feedback on the parts that need to move closer to your intended result."], ["Can you discuss documents or quality requirements?", "Yes. Share the product and market context so the team can identify which project-specific materials need to be discussed."]];
export default function FaqPage() { return <main><SiteHeader /><section className="listing-hero compact"><p className="eyebrow">FAQ</p><h1>Questions that help a project start clearly.</h1><p className="lead">For more specific requirements, send your brief so the conversation can be routed correctly.</p></section><section className="faq-list section">{questions.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={22} /></summary><p>{answer}</p></details>)}</section><section className="centered-cta"><h2>Have a different question?</h2><Link className="button" href="/contact">Contact our team <ArrowRight size={18} /></Link></section><SiteFooter /></main>; }
