"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AdminRangeFilter, RangePreset, formatChina, presetBounds, toRangeQuery } from "./AdminRangeFilter";

type Metrics={visitors:number;sessions:number;pageViews:number;leads:number;excluded:number};
type Visitor={id:string;anonymousId:string;country:string;source:string;visits:number;lastSeen:string;latestPage:string;classification:string;ipMasked:string};
type Lead={name:string;company:string;country:string;source:string;createdAt:string;status:string};
type Dashboard={metrics:Metrics;countries:{label:string;value:number}[];sources:{label:string;value:number}[];pages:{label:string;value:number}[];visitors:Visitor[];visitorTotal:number;leads:Lead[]};
const empty:Dashboard={metrics:{visitors:0,sessions:0,pageViews:0,leads:0,excluded:0},countries:[],sources:[],pages:[],visitors:[],visitorTotal:0,leads:[]};

export function AdminDashboard(){
 const router=useRouter(),initial=presetBounds("today");
 const [preset,setPreset]=useState<RangePreset>("today"),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[country,setCountry]=useState(""),[source,setSource]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[data,setData]=useState<Dashboard>(empty),[state,setState]=useState<"loading"|"ready"|"setup"|"error">("loading");
 function changePreset(next:RangePreset){setPreset(next);if(next!=="custom"){const b=presetBounds(next);setFrom(b.from);setTo(b.to);}setPage(1);}
 const load=useCallback(async()=>{setState("loading");const dates=toRangeQuery(from,to),query=new URLSearchParams({...dates,page:String(page),pageSize:String(pageSize)});if(country)query.set("country",country);if(source)query.set("source",source);const response=await fetch("/api/admin/overview?"+query,{cache:"no-store"});if(response.status===503){setState("setup");return;}if(!response.ok){setState("error");return;}const result=await response.json();setData(result.data??empty);setState("ready");},[from,to,country,source,page,pageSize]);
 useEffect(()=>{void load();},[load]);
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});router.replace("/admin/login");}
 const totalPages=Math.max(1,Math.ceil(data.visitorTotal/pageSize));
 return <main id="main-content" className="admin-main"><aside className="admin-sidebar"><a className="admin-brand" href="/admin"><span>SAI ZHAO</span><small>B2B GROWTH CONSOLE</small></a><nav aria-label="后台导航"><a className="active" href="#overview">数据总览</a><a href="/admin/visitors">流量与访客</a><a href="/admin/leads">询盘 CRM</a><a href="/admin/products">产品管理</a><a href="/admin/news">新闻与 SEO</a><a href="/admin/staff">员工与权限</a><a href="#quality">流量质量</a><a href="/admin/change-password">账号与密码</a></nav><div className="admin-sidebar-note"><b>真实数据口径</b><p>快捷时间、列表和报表均按中国标准时间筛选。</p></div></aside>
 <section className="admin-content"><header className="admin-header"><div><p className="admin-kicker">OPERATIONS OVERVIEW</p><h1>业务数据总览</h1></div><button className="admin-logout" onClick={logout}>退出登录</button></header>
 <AdminRangeFilter preset={preset} from={from} to={to} onPreset={changePreset} onFrom={setFrom} onTo={setTo} onApply={()=>{setPage(1);void load();}}/>
 <section className="admin-query-row"><label>国家 / 地区<input value={country} placeholder="如 AE、US、SA" onChange={e=>{setCountry(e.target.value.toUpperCase());setPage(1)}}/></label><label>来源渠道<input value={source} placeholder="如 google-organic" onChange={e=>{setSource(e.target.value);setPage(1)}}/></label><button onClick={()=>void load()}>应用筛选</button></section>
 {state==="setup"?<section className="admin-callout"><h2>数据层尚未连接</h2><p>后台不会显示模拟数据。完成数据库配置后，真实访问和询盘会自动入库。</p></section>:<><section id="overview" className="admin-metrics">{[["有效访客",data.metrics.visitors],["有效会话",data.metrics.sessions],["页面浏览",data.metrics.pageViews],["新增询盘",data.metrics.leads],["已排除流量",data.metrics.excluded]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{state==="loading"?"—":value}</strong><small>{label==="已排除流量"?"不计入经营报表":"当前时间范围"}</small></article>)}</section>
 {state==="error"?<section className="admin-callout"><h2>暂时无法读取数据</h2><p>请检查 Supabase 连接与管理员配置。</p></section>:<><section className="admin-grid"><Summary title="重点国家" rows={data.countries} onSelect={label=>{setCountry(label);setPage(1)}}/><Summary title="来源渠道" rows={data.sources} onSelect={label=>{setSource(label);setPage(1)}}/><Summary title="热门落地页" rows={data.pages}/></section>
 <section id="visitors" className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">VERIFIED VISITORS</p><h2>真实访客与访问轨迹</h2></div><div className="admin-table-actions"><label>每页<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option value={20}>20 条</option><option value={50}>50 条</option><option value={100}>100 条</option></select></label><a className="admin-row-action" href="/admin/visitors">访客中心</a></div></div><div className="admin-table-scroll"><table><thead><tr><th>访客</th><th>国家</th><th>脱敏 IP</th><th>来源</th><th>会话</th><th>最近页面</th><th>最近访问</th><th>分类</th><th></th></tr></thead><tbody>{data.visitors.length?data.visitors.map(v=><tr key={v.id||v.anonymousId}><td>{v.anonymousId}</td><td>{v.country||"Unknown"}</td><td>{v.ipMasked||"—"}</td><td>{v.source||"Direct"}</td><td>{v.visits}</td><td className="admin-path">{v.latestPage}</td><td>{formatChina(v.lastSeen)}</td><td><span className="admin-tag">{v.classification}</span></td><td>{v.id&&<a className="admin-row-action" href={"/admin/visitors/"+v.id}>详情</a>}</td></tr>):<tr><td colSpan={9} className="admin-empty">当前筛选条件下暂无有效访问。</td></tr>}</tbody></table></div><div className="admin-pagination"><span>共 {data.visitorTotal} 位访客 · 第 {page}/{totalPages} 页</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><button disabled={page===totalPages} onClick={()=>setPage(page+1)}>下一页</button></div></div></section>
 <section id="leads" className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">LEAD INBOX</p><h2>最新询盘</h2></div><a className="admin-row-action" href="/admin/leads">查看 CRM 分页列表</a></div><div className="admin-table-scroll"><table><thead><tr><th>联系人</th><th>公司</th><th>国家</th><th>来源</th><th>提交时间</th><th>状态</th></tr></thead><tbody>{data.leads.length?data.leads.map((lead,index)=><tr key={lead.createdAt+"-"+index}><td>{lead.name}</td><td>{lead.company}</td><td>{lead.country||"Unknown"}</td><td>{lead.source||"Direct"}</td><td>{formatChina(lead.createdAt)}</td><td><span className="admin-tag">{lead.status}</span></td></tr>):<tr><td colSpan={6} className="admin-empty">暂无询盘。</td></tr>}</tbody></table></div></section>
 <section id="quality" className="admin-quality"><div><p className="admin-kicker">DATA QUALITY</p><h2>真实流量，不混入测试数据。</h2></div><p>当前范围内有 <b>{data.metrics.excluded}</b> 条内部访问、预览环境、自动化测试、机器人或 Collects 类流量被排除。它们仅留作审计，不进入经营报表。</p></section></>}</>}</section></main>;
}
function Summary({title,rows,onSelect}:{title:string;rows:{label:string;value:number}[];onSelect?:(label:string)=>void}){return <section className="admin-summary"><h2>{title}</h2>{rows.length?<ol>{rows.map(row=><li key={row.label}><button onClick={()=>onSelect?.(row.label)} disabled={!onSelect}><span>{row.label}</span><b>{row.value}</b></button></li>)}</ol>:<p>暂无有效数据</p>}</section>;}
