"use client";
/* eslint-disable react-hooks/set-state-in-effect, @typescript-eslint/no-explicit-any */

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Eye, Funnel, MagnifyingGlass } from "@phosphor-icons/react";
import { AdminShell } from "@/components/admin/AdminShell";

type PageData<T> = { total: number; items: T[] };
type Visitor = { id: string; country: string; source: string; sessions: number; pageViews: number; lastSeen: string; latestPage: string };
type Lead = { id: string; name: string; company: string; email: string; country: string; application?: string; source: string; status: string; createdAt: string; nextFollowUpAt?: string | null };
const source = (value?: string) => ({ Direct: "直接访问", direct: "直接访问", "google-organic": "Google 自然搜索", "bing-organic": "Bing 自然搜索", linkedin: "LinkedIn" }[value ?? ""] ?? value ?? "直接访问");
const status = (value: string) => ({ New: "新询盘", Processing: "处理中", Contacted: "已联系", Qualified: "有效商机", Closed: "已完成", Invalid: "无效" }[value] ?? value);
function Pagination({ page, pageSize, total, onPage, onSize }: { page: number; pageSize: number; total: number; onPage: (value: number) => void; onSize: (value: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); const choices = Array.from({ length: Math.min(pages, 7) }, (_, i) => Math.max(1, Math.min(pages - 6, page - 3) + i)); return <div className="admin-pagination admin-pagination-full"><span>共 {total} 条 · 第 {page} / {pages} 页</span><div><label>每页<select value={pageSize} onChange={(e) => { onSize(Number(e.target.value)); onPage(1); }}><option value={20}>20 条</option><option value={50}>50 条</option><option value={100}>100 条</option></select></label><button disabled={page === 1} onClick={() => onPage(1)}>首页</button><button disabled={page === 1} onClick={() => onPage(page - 1)}>上一页</button>{choices.map((item) => <button className={item === page ? "active" : ""} key={item} onClick={() => onPage(item)}>{item}</button>)}<button disabled={page === pages} onClick={() => onPage(page + 1)}>下一页</button><button disabled={page === pages} onClick={() => onPage(pages)}>末页</button></div></div>; }

export function VisitorCenter() { const [data, setData] = useState<PageData<Visitor>>({ total: 0, items: [] }); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [q, setQ] = useState(""); const [country, setCountry] = useState(""); const [sourceValue, setSource] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize) }); if (q) params.set("q", q); if (country) params.set("country", country); if (sourceValue) params.set("source", sourceValue); const response = await fetch(`/api/admin/visitors?${params}`, { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (response.ok) setData(result.data); setLoading(false); }, [page, pageSize, q, country, sourceValue]); useEffect(() => { void load(); }, [load]);
  return <AdminShell><section className="admin-content admin-content-wide"><header className="admin-header"><div><p className="admin-kicker">SAI ZHAO · VISITORS</p><h1>访客中心</h1><p className="admin-subtitle">查看真实、已记录的访问情况与页面轨迹。</p></div></header><section className="admin-filters"><label>关键词<input value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} placeholder="国家、来源或页面" /></label><label>国家 / 地区<input value={country} onChange={(e) => { setCountry(e.target.value.toUpperCase()); setPage(1); }} /></label><label>来源渠道<input value={sourceValue} onChange={(e) => { setSource(e.target.value); setPage(1); }} /></label><button onClick={() => void load()}><Funnel weight="bold" />筛选</button></section><section className="admin-panel"><div className="admin-panel-heading"><div><h2>访客记录</h2><p className="admin-panel-subtitle">按访客汇总，不显示个人身份或 IP 信息。</p></div></div><div className="admin-table-scroll"><table><thead><tr><th>国家/地区</th><th>来源</th><th>会话</th><th>页面浏览</th><th>最近页面</th><th>最近访问</th><th>操作</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="admin-empty">正在读取数据…</td></tr> : data.items.length ? data.items.map((item) => <tr key={item.id}><td>{item.country}</td><td>{source(item.source)}</td><td>{item.sessions}</td><td>{item.pageViews}</td><td className="admin-path">{item.latestPage}</td><td>{item.lastSeen}</td><td><Link className="admin-row-action" href={`/admin/visitors/${item.id}`}><Eye weight="bold" />查看详情</Link></td></tr>) : <tr><td colSpan={7} className="admin-empty">暂无符合条件的访客记录</td></tr>}</tbody></table></div><Pagination page={page} pageSize={pageSize} total={data.total} onPage={setPage} onSize={setPageSize} /></section></section></AdminShell>; }

export function InquiryCenter() { const [data, setData] = useState<PageData<Lead>>({ total: 0, items: [] }); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [q, setQ] = useState(""); const [statusValue, setStatus] = useState(""); const [loading, setLoading] = useState(true);
 const load = useCallback(async () => { setLoading(true); const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize) }); if (q) params.set("q", q); if (statusValue) params.set("status", statusValue); const response = await fetch(`/api/admin/inquiries?${params}`, { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (response.ok) setData(result.data); setLoading(false); }, [page, pageSize, q, statusValue]); useEffect(() => { void load(); }, [load]);
 return <AdminShell><section className="admin-content admin-content-wide"><header className="admin-header"><div><p className="admin-kicker">SAI ZHAO · INQUIRIES</p><h1>询盘管理</h1><p className="admin-subtitle">集中跟进客户需求，并关联提交前的真实访问轨迹。</p></div></header><section className="admin-filters"><label>关键词<input value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} placeholder="姓名、公司或邮箱" /></label><label>处理状态<select value={statusValue} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">全部状态</option>{["New", "Processing", "Contacted", "Qualified", "Closed", "Invalid"].map((item) => <option key={item} value={item}>{status(item)}</option>)}</select></label><button onClick={() => void load()}><MagnifyingGlass weight="bold" />筛选</button></section><section className="admin-panel"><div className="admin-table-scroll"><table><thead><tr><th>客户</th><th>公司</th><th>国家/地区</th><th>产品应用</th><th>来源</th><th>提交时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="admin-empty">正在读取询盘…</td></tr> : data.items.length ? data.items.map((item) => <tr key={item.id}><td><b>{item.name}</b><small>{item.email}</small></td><td>{item.company}</td><td>{item.country}</td><td>{item.application || "—"}</td><td>{source(item.source)}</td><td>{item.createdAt}</td><td><span className="admin-tag">{status(item.status)}</span></td><td><Link className="admin-row-action" href={`/admin/inquiries/${item.id}`}>查看详情</Link></td></tr>) : <tr><td colSpan={8} className="admin-empty">暂无符合条件的询盘</td></tr>}</tbody></table></div><Pagination page={page} pageSize={pageSize} total={data.total} onPage={setPage} onSize={setPageSize} /></section></section></AdminShell>; }

export function VisitorDetail({ id }: { id: string }) { const [data, setData] = useState<any>(null); useEffect(() => { void fetch(`/api/admin/visitors/${id}`).then((r) => r.json()).then((r) => setData(r.data ?? null)); }, [id]); return <AdminShell><section className="admin-content admin-content-wide"><Link className="admin-text-link" href="/admin/visitors"><ArrowLeft weight="bold" />返回访客中心</Link><header className="admin-header admin-detail-header"><div><p className="admin-kicker">VISITOR JOURNEY</p><h1>访问详情</h1><p className="admin-subtitle">{data?.visitor ? `首次访问 ${data.visitor.firstSeen} · 最近访问 ${data.visitor.lastSeen}` : "正在读取访问轨迹…"}</p></div></header><section className="admin-grid"><Summary title="访问会话" value={data?.sessions?.length ?? "—"} /><Summary title="页面事件" value={data?.events?.length ?? "—"} /><Summary title="关联询盘" value={data?.leads?.length ?? "—"} /></section><section className="admin-panel"><h2>页面访问轨迹</h2><div className="admin-timeline">{data?.events?.length ? data.events.map((event: any, i: number) => <div key={i}><time>{event.at}</time><b>{event.page}</b><span>{event.title || "页面浏览"}</span></div>) : <p className="admin-empty">暂无可展示的页面访问轨迹</p>}</div></section><section className="admin-panel"><h2>关联询盘</h2>{data?.leads?.length ? data.leads.map((lead: any) => <Link key={lead.id} className="admin-related-link" href={`/admin/inquiries/${lead.id}`}>{lead.name} · {lead.company} <span>{status(lead.status)}</span></Link>) : <p className="admin-empty">该匿名访客暂未关联到询盘。</p>}</section></section></AdminShell>; }
function Summary({ title, value }: { title: string; value: string | number }) { return <section className="admin-summary"><h2>{title}</h2><strong className="admin-summary-number">{value}</strong></section>; }

export function InquiryDetail({ id }: { id: string }) { const [data, setData] = useState<any>(null); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); const load = useCallback(async () => { const response = await fetch(`/api/admin/inquiries/${id}`); const result = await response.json().catch(() => ({})); setData(result.data ?? null); }, [id]); useEffect(() => { void load(); }, [load]); const update = async (body: Record<string, unknown>) => { setSaving(true); await fetch(`/api/admin/inquiries/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setSaving(false); void load(); }; const addNote = async () => { if (!note.trim()) return; setSaving(true); await fetch(`/api/admin/inquiries/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ note }) }); setNote(""); setSaving(false); void load(); };
 const lead = data?.lead; return <AdminShell><section className="admin-content admin-content-wide"><Link className="admin-text-link" href="/admin/inquiries"><ArrowLeft weight="bold" />返回询盘管理</Link><header className="admin-header admin-detail-header"><div><p className="admin-kicker">INQUIRY DETAIL</p><h1>{lead?.company || "询盘详情"}</h1><p className="admin-subtitle">{lead ? `${lead.name} · ${lead.created_at ? new Date(lead.created_at).toLocaleString("zh-CN") : ""}` : "正在读取客户信息…"}</p></div></header>{lead && <><section className="admin-detail-grid"><section className="admin-panel"><h2>客户信息</h2><dl className="admin-detail-list"><dt>联系人</dt><dd>{lead.name}</dd><dt>邮箱</dt><dd><a href={`mailto:${lead.email}`}>{lead.email}</a></dd><dt>电话</dt><dd>{lead.phone || "—"}</dd><dt>国家/地区</dt><dd>{lead.country_name || lead.country_code || "—"}</dd><dt>产品应用</dt><dd>{lead.application || "—"}</dd><dt>需求说明</dt><dd className="admin-detail-brief">{lead.brief}</dd></dl></section><section className="admin-panel"><h2>跟进处理</h2><label className="admin-field">状态<select value={lead.status} disabled={saving} onChange={(e) => void update({ status: e.target.value })}>{["New", "Processing", "Contacted", "Qualified", "Closed", "Invalid"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="admin-field">下次跟进<input type="datetime-local" disabled={saving} value={lead.next_follow_up_at ? new Date(lead.next_follow_up_at).toISOString().slice(0, 16) : ""} onChange={(e) => void update({ nextFollowUpAt: e.target.value || null })} /></label><label className="admin-field">新增跟进<textarea value={note} onChange={(e) => setNote(e.target.value)} rows={5} placeholder="记录本次沟通结果" /></label><button className="admin-primary" disabled={saving} onClick={() => void addNote()}>保存跟进记录</button></section></section><section className="admin-panel"><h2>跟进记录</h2><div className="admin-timeline">{data.notes?.length ? data.notes.map((item: any) => <div key={item.id}><time>{item.createdAt}</time><b>{item.stage || "跟进"}</b><span>{item.note}</span></div>) : <p className="admin-empty">暂无跟进记录</p>}</div></section>{lead.visitorId && <section className="admin-panel"><h2>提交前访问轨迹</h2><p className="admin-panel-subtitle">该询盘已与已同意统计的匿名访问记录关联。</p><Link className="admin-row-action" href={`/admin/visitors/${lead.visitorId}`}>查看完整访问轨迹</Link></section>}</>}</section></AdminShell>; }
