"use client";
import { useEffect, useState } from "react";
import { AdminRangeFilter, RangePreset, formatChina, toRangeQuery } from "./AdminRangeFilter";

type Lead={id:string;created_at:string;status:string;name:string;email:string;company:string;application?:string;country_code?:string;country_name?:string;phone?:string;page_path?:string;source?:string;medium?:string;campaign?:string;anonymous_id?:string;next_follow_up_at?:string};
const stages=["New","Contacted","Qualified","Sample","Quote","Negotiation","Won","Lost"];
export function LeadManager(){
  const [items,setItems]=useState<Lead[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[message,setMessage]=useState("");
  const [range,setRange]=useState<RangePreset>("month"),[customStart,setCustomStart]=useState(""),[customEnd,setCustomEnd]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[source,setSource]=useState(""),[country,setCountry]=useState("");
  async function load(){const p=new URLSearchParams({page:String(page),pageSize:String(pageSize)}),dates=toRangeQuery(range,customStart,customEnd);p.set("from",dates.from);p.set("to",dates.to);if(query.trim())p.set("q",query.trim());if(status)p.set("status",status);if(source.trim())p.set("source",source.trim());if(country.trim())p.set("country",country.trim().toUpperCase());const r=await fetch("/api/admin/leads?"+p.toString(),{cache:"no-store"}),j=await r.json();if(r.ok){setItems(j.data??[]);setTotal(j.total??0);}else setMessage(j.message??"读取失败。");}
  useEffect(()=>{void load();},[page,pageSize,range,customStart,customEnd,query,status,source,country]);
  const pages=Math.max(1,Math.ceil(total/pageSize));
  return <main className="admin-content admin-content-wide"><header className="admin-header"><div><p className="admin-kicker">INQUIRY CRM</p><h1>客户询盘</h1><p className="admin-subtitle">仅显示官网真实表单入库的询盘，并保留来源、落地页与后续跟进信息。</p></div><a className="admin-logout" href="/admin">返回数据总览</a></header><section className="admin-panel admin-list-panel"><AdminRangeFilter value={range} customStart={customStart} customEnd={customEnd} onPresetChange={v=>{setRange(v);setPage(1)}} onCustomStartChange={v=>{setCustomStart(v);setRange("custom");setPage(1)}} onCustomEndChange={v=>{setCustomEnd(v);setRange("custom");setPage(1)}}/><div className="admin-query-row"><label>搜索<input value={query} placeholder="姓名、公司或邮箱" onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><label>阶段<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">全部阶段</option>{stages.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>来源<input value={source} placeholder="例如 google" onChange={e=>{setSource(e.target.value);setPage(1)}}/></label><label>国家代码<input value={country} maxLength={2} placeholder="US" onChange={e=>{setCountry(e.target.value);setPage(1)}}/></label><label>每页<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option value={20}>20 条</option><option value={50}>50 条</option><option value={100}>100 条</option></select></label></div><div className="admin-panel-heading"><div><p className="admin-kicker">REAL WEBSITE LEADS</p><h2>询盘列表</h2></div><span className="admin-tag">真实数据</span></div><div className="admin-table-scroll"><table><thead><tr><th>客户</th><th>公司 / 国家</th><th>阶段</th><th>来源与活动</th><th>落地页</th><th>创建时间</th><th>下次跟进</th></tr></thead><tbody>{items.length?items.map(item=><tr key={item.id}><td><b>{item.name}</b><small>{item.email}{item.phone?" · "+item.phone:""}</small></td><td>{item.company}<small>{item.country_name??item.country_code??"—"}</small></td><td><span className="admin-tag">{item.status}</span></td><td>{item.source??"Direct"}<small>{[item.medium,item.campaign].filter(Boolean).join(" / ")||"—"}</small></td><td><code>{item.page_path??"—"}</code></td><td>{formatChina(item.created_at)}</td><td>{item.next_follow_up_at?formatChina(item.next_follow_up_at):"—"}</td></tr>):<tr><td colSpan={7} className="admin-empty">此筛选范围没有真实询盘。</td></tr>}</tbody></table></div><div className="admin-pagination"><span>共 {total} 条 · 第 {page}/{pages} 页</span><div><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>上一页</button><button disabled={page===pages} onClick={()=>setPage(v=>v+1)}>下一页</button></div></div>{message&&<p className="admin-feedback">{message}</p>}</section></main>;
}