"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
type Zone = { country_code: string; country_name: string; rate_minor: number; free_over_minor: number | null; tax_rate_bps: number; estimated_days: string | null; enabled: boolean };
const blank: Zone = { country_code: "", country_name: "", rate_minor: 0, free_over_minor: null, tax_rate_bps: 0, estimated_days: null, enabled: false };
export function RetailShippingManager() {
  const [zones, setZones] = useState<Zone[]>([]); const [form, setForm] = useState<Zone>(blank); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/admin/retail/shipping", { cache: "no-store" }); const result = await response.json(); if (response.ok) setZones(result.data); else setMessage(result.message); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); const response = await fetch("/api/admin/retail/shipping", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); setBusy(false); setMessage(response.ok ? "配送区域已保存。" : result.message); if (response.ok) { setForm(blank); void load(); } }
  return <AdminShell><section id="main-content" className="admin-content admin-content-wide"><header className="admin-header"><div><h1>配送区域</h1><p className="admin-subtitle">仅开启可实际配送的国家。运费与税率以已审核的商业规则为准。</p></div></header><section className="admin-split"><form className="admin-editor" onSubmit={save}><h2>{form.country_code ? `编辑 ${form.country_code}` : "新增区域"}</h2><div className="admin-form-grid"><label>国家代码（ISO 2 位）<input required maxLength={2} value={form.country_code} onChange={(e) => setForm({ ...form, country_code: e.target.value.toUpperCase() })} /></label><label>国家名称<input required value={form.country_name} onChange={(e) => setForm({ ...form, country_name: e.target.value })} /></label><label>运费（美元分）<input type="number" min="0" required value={form.rate_minor} onChange={(e) => setForm({ ...form, rate_minor: Number(e.target.value) })} /></label><label>满额免运费（美元分，可留空）<input type="number" min="0" value={form.free_over_minor ?? ""} onChange={(e) => setForm({ ...form, free_over_minor: e.target.value === "" ? null : Number(e.target.value) })} /></label><label>税率（基点，100=1%）<input type="number" min="0" max="10000" value={form.tax_rate_bps} onChange={(e) => setForm({ ...form, tax_rate_bps: Number(e.target.value) })} /></label><label>预计送达时间<input value={form.estimated_days || ""} onChange={(e) => setForm({ ...form, estimated_days: e.target.value })} /></label><label>状态<select value={form.enabled ? "on" : "off"} onChange={(e) => setForm({ ...form, enabled: e.target.value === "on" })}><option value="off">关闭</option><option value="on">开启</option></select></label></div><button className="admin-primary" disabled={busy}>{busy ? "保存中…" : "保存区域"}</button><p role="status" className="admin-feedback">{message}</p></form><section className="admin-panel admin-list-panel"><h2>已配置区域</h2><div className="admin-table-scroll"><table><thead><tr><th>国家</th><th>运费</th><th>税率</th><th>状态</th><th>操作</th></tr></thead><tbody>{zones.length ? zones.map((z) => <tr key={z.country_code}><td>{z.country_name} ({z.country_code})</td><td>${(z.rate_minor / 100).toFixed(2)}</td><td>{(z.tax_rate_bps / 100).toFixed(2)}%</td><td>{z.enabled ? "已开启" : "已关闭"}</td><td><button type="button" onClick={() => setForm(z)}>编辑</button></td></tr>) : <tr><td colSpan={5}>暂无配送区域，零售结算不可用。</td></tr>}</tbody></table></div></section></section></section></AdminShell>;
}
