"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { AdminShell } from "@/components/admin/AdminShell";
import { emptyProductDetail, type ProductImage, type RetailProduct, type RetailVariant } from "@/lib/retail-types";

const toRows = (value: { label: string; value: string }[]) => value.map((v) => `${v.label}: ${v.value}`).join("\n");
const fromRows = (value: string) => value.split("\n").map((line) => { const i = line.indexOf(":"); return { label: i < 0 ? line : line.slice(0, i), value: i < 0 ? "" : line.slice(i + 1).replace(/^ /, "") }; });
const toLines = (value: string[]) => value.join("\n");
const fromLines = (value: string) => value.split("\n");
export function RetailProductEditor({ id }: { id: string }) {
  const [product, setProduct] = useState<RetailProduct | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch(`/api/admin/retail/products/${id}`, { cache: "no-store" }).then((r) => r.json()).then((v) => setProduct(v.data ?? null)).catch(() => setMessage("无法加载产品。")); }, [id]);
  function update<K extends keyof RetailProduct>(key: K, value: RetailProduct[K]) { setProduct((p) => p ? { ...p, [key]: value } : p); }
  function detail<K extends keyof typeof emptyProductDetail>(key: K, value: typeof emptyProductDetail[K]) { setProduct((p) => p ? { ...p, detail: { ...p.detail, [key]: value } } : p); }
  async function upload(file: File, target: "cover_url" | "hero_url" | "gallery" | "application" | "packaging" | "download") {
    setBusy(true); setMessage("");
    const form = new FormData(); form.set("file", file);
    const response = await fetch("/api/admin/media", { method: "POST", body: form }); const result = await response.json();
    if (response.ok) {
      const url = result.data.public_url as string;
      if (target === "gallery") setProduct((p) => p ? { ...p, gallery: [...p.gallery, { url, alt: p.title }] } : p);
      else if (target === "application") setProduct((p) => p ? { ...p, detail: { ...p.detail, applications: [...p.detail.applications, { title: "Application", description: "", image: url, alt: "" }] } } : p);
      else if (target === "packaging") detail("packagingImage", url);
      else if (target === "download") setProduct((p) => p ? { ...p, detail: { ...p.detail, downloads: [...p.detail.downloads, { title: file.name, url, note: "" }] } } : p);
      else update(target, url);
    } else setMessage(result.message ?? "上传失败。");
    setBusy(false);
  }
  function changeVariant(index: number, key: keyof RetailVariant, value: string | number | boolean) {
    setProduct((p) => p ? { ...p, variants: p.variants.map((v, i) => i === index ? { ...v, [key]: value } : v) } : p);
  }
  async function save(event: FormEvent) {
    event.preventDefault(); if (!product) return; setBusy(true); setMessage("");
    const response = await fetch(`/api/admin/retail/products/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(product) });
    const result = await response.json(); setBusy(false); setMessage(response.ok ? "已保存。可打开预览检查页面。" : result.message ?? "保存失败。");
    if (response.ok) { const fresh = await fetch(`/api/admin/retail/products/${id}`, { cache: "no-store" }); setProduct((await fresh.json()).data); }
  }
  return <AdminShell><section id="main-content" className="admin-content admin-content-wide"><header className="admin-header"><div><h1>商品编辑</h1><p className="admin-subtitle">编辑零售商品的文案、图片、规格、库存和详情板块</p></div><div><Link className="admin-primary" href={`/admin/products/preview/${id}`} target="_blank">预览商品页</Link></div></header>
    {!product ? <p>{message || "正在加载商品…"}</p> : <form className="admin-editor retail-admin-editor" onSubmit={save}>
      {product.is_demo && <p className="admin-feedback">这是设计示例草稿，不能直接发布或购买。请用真实产品资料另建商品。</p>}
      <h2>基础信息</h2><div className="admin-form-grid"><label>商品名称<input required value={product.title} onChange={(e) => update("title", e.target.value)} /></label><label>页面地址<input required value={product.slug} onChange={(e) => update("slug", e.target.value)} /></label><label>副标题<input value={product.subtitle || ""} onChange={(e) => update("subtitle", e.target.value)} /></label><label>角标<input value={product.badge || ""} onChange={(e) => update("badge", e.target.value)} /></label></div>
      <label>商品简介<textarea rows={3} value={product.summary || ""} onChange={(e) => update("summary", e.target.value)} /></label><label>正文<textarea rows={4} value={product.content} onChange={(e) => update("content", e.target.value)} /></label>
      <div className="admin-form-grid"><label>发布状态<select value={product.status} onChange={(e) => update("status", e.target.value as RetailProduct["status"])} disabled={product.is_demo}><option value="draft">草稿</option><option value="review">待审核</option><option value="published">已发布</option><option value="archived">已归档</option></select></label><label>零售开关<select value={product.retail_enabled ? "yes" : "no"} onChange={(e) => update("retail_enabled", e.target.value === "yes")}><option value="no">关闭</option><option value="yes">开启</option></select></label></div>
      <h2>商品图片</h2><div className="admin-form-grid"><label>主图<input type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], "cover_url")} />{product.cover_url && <small>{product.cover_url}</small>}</label><label>首屏大图<input type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], "hero_url")} />{product.hero_url && <small>{product.hero_url}</small>}</label></div><label>图片画廊（可多次上传）<input type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], "gallery")} /></label><div className="retail-admin-gallery">{product.gallery.map((image: ProductImage, index) => <div key={`${image.url}-${index}`}><Image src={image.url} alt={image.alt} width={150} height={120} /><input aria-label={`图片 ${index + 1} 的说明`} value={image.alt} onChange={(e) => update("gallery", product.gallery.map((v, i) => i === index ? { ...v, alt: e.target.value } : v))} /><button type="button" onClick={() => update("gallery", product.gallery.filter((_, i) => i !== index))}>移除</button></div>)}</div>
      <h2>购买规格与库存</h2>{product.variants.map((v, index) => <div className="retail-admin-variant" key={v.id || index}><div className="admin-form-grid"><label>SKU<input value={v.sku} onChange={(e) => changeVariant(index, "sku", e.target.value)} /></label><label>规格名称<input value={v.label} onChange={(e) => changeVariant(index, "label", e.target.value)} /></label><label>价格（美元分）<input type="number" min="0" value={v.price_minor} onChange={(e) => changeVariant(index, "price_minor", Number(e.target.value))} /></label><label>可售库存<input type="number" min={v.reserved_quantity} value={v.stock_quantity} onChange={(e) => changeVariant(index, "stock_quantity", Number(e.target.value))} /></label><label>重量（克）<input type="number" min="0" value={v.weight_grams} onChange={(e) => changeVariant(index, "weight_grams", Number(e.target.value))} /></label><label>状态<select value={v.is_active ? "yes" : "no"} onChange={(e) => changeVariant(index, "is_active", e.target.value === "yes")}><option value="yes">上架</option><option value="no">下架</option></select></label></div></div>)}<button type="button" onClick={() => update("variants", [...product.variants, { id: "", product_id: id, sku: "", label: "", price_minor: 0, compare_at_minor: null, currency: "USD", stock_quantity: 0, reserved_quantity: 0, weight_grams: 0, image_url: null, is_active: false, sort_order: product.variants.length }])}>添加规格</button>
      <h2>详情板块</h2><label>首屏标题<input value={product.detail.heroLine} onChange={(e) => detail("heroLine", e.target.value)} /></label><label>首屏说明<input value={product.detail.heroDescription} onChange={(e) => detail("heroDescription", e.target.value)} /></label><label>默认展示规格 SKU<input value={product.detail.defaultVariantSku} onChange={(e) => detail("defaultVariantSku", e.target.value)} /></label><label>产品介绍<textarea rows={5} value={product.detail.overview} onChange={(e) => detail("overview", e.target.value)} /></label><div className="admin-form-grid"><label>前调<input value={product.detail.topNotes} onChange={(e) => detail("topNotes", e.target.value)} /></label><label>中调<input value={product.detail.heartNotes} onChange={(e) => detail("heartNotes", e.target.value)} /></label><label>后调<input value={product.detail.baseNotes} onChange={(e) => detail("baseNotes", e.target.value)} /></label></div>
      <div className="admin-form-grid"><label>技术参数（每行：名称: 内容）<textarea rows={8} value={toRows(product.detail.technical)} onChange={(e) => detail("technical", fromRows(e.target.value))} /></label><label>建议用量（每行：应用: 数值）<textarea rows={8} value={toRows(product.detail.dosage)} onChange={(e) => detail("dosage", fromRows(e.target.value))} /></label><label>储存建议（每行一项）<textarea rows={6} value={toLines(product.detail.storage)} onChange={(e) => detail("storage", fromLines(e.target.value))} /></label><label>运输信息（每行一项）<textarea rows={6} value={toLines(product.detail.shipping)} onChange={(e) => detail("shipping", fromLines(e.target.value))} /></label></div>
      <label>应用场景图片<input type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], "application")} /></label>{product.detail.applications.map((app, index) => <div className="retail-admin-application" key={`${app.image}-${index}`}><Image src={app.image} alt={app.alt} width={80} height={70} /><input aria-label="场景名称" value={app.title} onChange={(e) => detail("applications", product.detail.applications.map((v, i) => i === index ? { ...v, title: e.target.value } : v))} /><input aria-label="场景说明" value={app.description} onChange={(e) => detail("applications", product.detail.applications.map((v, i) => i === index ? { ...v, description: e.target.value } : v))} /><input aria-label="图片替代文字" value={app.alt} onChange={(e) => detail("applications", product.detail.applications.map((v, i) => i === index ? { ...v, alt: e.target.value } : v))} /><button type="button" onClick={() => detail("applications", product.detail.applications.filter((_, i) => i !== index))}>移除</button></div>)}
      <label>包装介绍<input value={product.detail.packagingIntro} onChange={(e) => detail("packagingIntro", e.target.value)} /></label><label>包装图<input type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], "packaging")} />{product.detail.packagingImage && <small>{product.detail.packagingImage}</small>}</label><div className="admin-form-grid"><label>零售优势（每行一项）<textarea rows={4} value={toLines(product.detail.retailBenefits)} onChange={(e) => detail("retailBenefits", fromLines(e.target.value))} /></label><label>定制优势（每行一项）<textarea rows={4} value={toLines(product.detail.customBenefits)} onChange={(e) => detail("customBenefits", fromLines(e.target.value))} /></label></div>
      <h2>资料下载与常见问题</h2><label>上传资料（PDF）<input type="file" accept="application/pdf" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], "download")} /></label>{product.detail.downloads.map((file, index) => <div className="admin-form-grid" key={`${file.url}-${index}`}><label>显示名称<input value={file.title} onChange={(e) => detail("downloads", product.detail.downloads.map((v, i) => i === index ? { ...v, title: e.target.value } : v))} /></label><label>说明<input value={file.note} onChange={(e) => detail("downloads", product.detail.downloads.map((v, i) => i === index ? { ...v, note: e.target.value } : v))} /></label><button type="button" onClick={() => detail("downloads", product.detail.downloads.filter((_, i) => i !== index))}>移除资料</button></div>)}{product.detail.faqs.map((faq, index) => <div className="admin-form-grid" key={index}><label>问题<input value={faq.question} onChange={(e) => detail("faqs", product.detail.faqs.map((v, i) => i === index ? { ...v, question: e.target.value } : v))} /></label><label>回答<input value={faq.answer} onChange={(e) => detail("faqs", product.detail.faqs.map((v, i) => i === index ? { ...v, answer: e.target.value } : v))} /></label></div>)}<button type="button" onClick={() => detail("faqs", [...product.detail.faqs, { question: "", answer: "" }])}>添加问题</button><label>相关商品 Slug（每行一个）<textarea rows={3} value={toLines(product.detail.relatedSlugs)} onChange={(e) => detail("relatedSlugs", fromLines(e.target.value))} /></label><h2>搜索展示</h2><div className="admin-form-grid"><label>SEO 标题<input value={product.seo_title || ""} onChange={(e) => update("seo_title", e.target.value)} /></label><label>SEO 描述<textarea rows={2} value={product.seo_description || ""} onChange={(e) => update("seo_description", e.target.value)} /></label></div>
      <button className="admin-primary" disabled={busy}>{busy ? "正在保存…" : "保存商品"}</button><p role="status" className="admin-feedback">{message}</p>
    </form>}
  </section></AdminShell>;
}
