"use client";
import { useCallback, useEffect, useState } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import { formatMoney } from "@/lib/retail-types";
type Order = { id: string; order_number: string; buyer_name: string; buyer_email: string; country_code: string; total_minor: number; currency: string; status: string; fulfillment_status: string; tracking_number: string | null; carrier: string | null; created_at: string; retail_order_items: { id: string; product_title: string; variant_label: string; quantity: number; line_total_minor: number }[] };
export function RetailOrdersManager({ canManage }: { canManage: boolean }) {
  const [orders, setOrders] = useState<Order[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [status, setStatus] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/admin/retail/orders?page=${page}&pageSize=10${status ? `&status=${status}` : ""}`, { cache: "no-store" }); const result = await response.json(); if (response.ok) { setOrders(result.data); setTotal(result.total); } else setMessage(result.message); }, [page, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function save(order: Order, fulfillment_status: string, carrier: string, tracking_number: string) { const response = await fetch(`/api/admin/retail/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fulfillment_status, carrier, tracking_number }) }); const result = await response.json(); setMessage(response.ok ? "订单已更新。" : result.message); if (response.ok) void load(); }
  return <AdminShell><section id="main-content" className="admin-content admin-content-wide"><header className="admin-header"><div><h1>零售订单</h1><p className="admin-subtitle">仅显示真实结算订单；支付与履约状态分别记录。</p></div></header><div className="admin-panel"><label>筛选状态 <select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">全部</option><option value="pending">待支付</option><option value="paid">已支付</option><option value="cancelled">已取消</option><option value="expired">已过期</option><option value="refunded">已退款</option></select></label><p role="status" className="admin-feedback">{message}</p>{orders.length ? orders.map((order) => <OrderCard key={order.id} order={order} save={save} canManage={canManage} />) : <p className="admin-empty">暂无订单</p>}<div className="admin-pagination"><span>共 {total} 条 · 第 {page}/{Math.max(1, Math.ceil(total / 10))} 页</span><div><button disabled={page === 1} onClick={() => setPage(page - 1)}>上一页</button><button disabled={page * 10 >= total} onClick={() => setPage(page + 1)}>下一页</button></div></div></div></section></AdminShell>;
}
function OrderCard({ order, save, canManage }: { order: Order; save: (order: Order, fulfillment: string, carrier: string, tracking: string) => Promise<void>; canManage: boolean }) {
  const [fulfillment, setFulfillment] = useState(order.fulfillment_status); const [carrier, setCarrier] = useState(order.carrier || ""); const [tracking, setTracking] = useState(order.tracking_number || "");
  return <article className="retail-admin-order"><header><strong>{order.order_number}</strong><span>{new Date(order.created_at).toLocaleString("zh-CN")}</span><b>{formatMoney(order.total_minor, order.currency)}</b></header><p>{order.buyer_name} · {order.buyer_email} · {order.country_code}</p><p>支付：{order.status} · 履约：{order.fulfillment_status}</p><ul>{order.retail_order_items.map((item) => <li key={item.id}>{item.product_title} · {item.variant_label} × {item.quantity} — {formatMoney(item.line_total_minor)}</li>)}</ul>{order.status === "paid" && canManage && <div className="retail-order-actions"><select aria-label="履约状态" value={fulfillment} onChange={(e) => setFulfillment(e.target.value)}><option value="unfulfilled">未履约</option><option value="packed">已打包</option><option value="shipped">已发货</option><option value="delivered">已送达</option></select><input placeholder="承运商" aria-label="承运商" value={carrier} onChange={(e) => setCarrier(e.target.value)} /><input placeholder="运单号" aria-label="运单号" value={tracking} onChange={(e) => setTracking(e.target.value)} /><button type="button" onClick={() => void save(order, fulfillment, carrier, tracking)}>保存</button></div>}</article>;
}
