"use client";
import { useCallback,useEffect,useState } from "react";
import { AdminRangeFilter,RangePreset,formatChina,presetBounds,toRangeQuery } from "./AdminRangeFilter";

type Visitor={id:string;anonymousId:string;ipMasked:string;sessionCount:number;firstSeenAt:string;lastSeenAt:string;country:string;firstSource:string;latestSource:string;firstLandingPage:string;classification:string};
type Result={items:Visitor[];total:number;page:number;pageSize:number};
const empty:Result={items:[],total:0,page:1,pageSize:20};
export function VisitorExplorer(){
 const initial=presetBounds("month");const [preset,setPreset]=useState<RangePreset>("month"),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[country,setCountry]=useState(""),[source,setSource]=useState(""),[q,setQ]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[data,setData]=useState<Result>(empty),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 function changePreset(next:RangePreset){setPreset(next);if(next!=="custom"){const b=presetBounds(next);setFrom(b.from);setTo(b.to);}setPage(1);}
 const load=useCallback(async()=>{setLoading(true);const dates=toRangeQuery(from,to),params=new URLSearchParams({...dates,page:String(page),pageSize:String(pageSize)});if(country)params.set("country",country);if(source)params.set("source",source);if(q)params.set("q",q);const r=await fetch("/api/admin/visitors?"+params,{cache:"no-store"});const j=await r.json();if(r.ok){setData(j.data);setMessage("");}else setMessage(j.message??"读取失败。");setLoading(false);},[from,to,country,source,q,page,pageSize]);
 useEffect(()=>{void load();},[load]);const totalPages=Math.max(1,Math.ceil(data.total/pageSize));
 return <main className="admin-content admin-content-wide"><header className="admin-header"><div><p className="admin-kicker">VISITOR INTELLIGENCE</p><h1>访客中心</h1><p className="admin-subtitle">按同一站点访客归属会话，查看真实访问来源、路径与询盘关联。</p></div><a className="admin-logout" href="/admin">返回总览</a></header>
 <AdminRangeFilter preset={preset} from={from} to={to} onPreset={changePreset} onFrom={setFrom} onTo={setTo} onApply={()=>{setPage(1);void load();}}/>
 <section className="admin-query-row"><label>搜索访客<input value={q} placeholder="访客编号或脱敏 IP" onChange={e=>{setQ(e.target.value);setPage(1)}}/></label><label>国家<input value={country} placeholder="如 US、AE" onChange={e=>{setCountry(e.target.value.toUpperCase());setPage(1)}}/></label><label>来源<input value={source} placeholder="如 google-organic" onChange={e=>{setSource(e.target.value);setPage(1)}}/></label><button onClick={()=>void load()}>应用筛选</button></section>
 <section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">VERIFIED VISITORS</p><h2>客户访问归属</h2></div><label>每页<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option value={20}>20 条</option><option value={50}>50 条</option><option value={100}>100 条</option></select></label></div>
 <div className="admin-table-scroll"><table><thead><tr><th>访客</th><th>国家</th><th>脱敏 IP</th><th>首次来源</th><th>最近来源</th><th>会话</th><th>首次落地页</th><th>最近访问</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="admin-empty">正在加载真实数据…</td></tr>:data.items.length?data.items.map(v=><tr key={v.id}><td><b>{v.anonymousId}</b><small>{v.classification} · 首次 {formatChina(v.firstSeenAt)}</small></td><td>{v.country}</td><td>{v.ipMasked||"—"}</td><td>{v.firstSource}</td><td>{v.latestSource}</td><td>{v.sessionCount}</td><td className="admin-path">{v.firstLandingPage}</td><td>{formatChina(v.lastSeenAt)}</td><td><a className="admin-row-action" href={"/admin/visitors/"+v.id+"?range="+preset+"&from="+from+"&to="+to}>访问详情</a></td></tr>):<tr><td colSpan={9} className="admin-empty">{message||"当前筛选条件下暂无有效访客。"}</td></tr>}</tbody></table></div>
 <Pagination total={data.total} page={page} totalPages={totalPages} pageSize={pageSize} setPage={setPage}/></section></main>;
}
export function Pagination({total,page,totalPages,pageSize,setPage}:{total:number;page:number;totalPages:number;pageSize:number;setPage:(value:number)=>void}){return <div className="admin-pagination"><span>共 {total} 条 · 每页 {pageSize} 条 · 第 {page}/{totalPages} 页</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><button disabled={page>=totalPages} onClick={()=>setPage(page+1)}>下一页</button></div></div>;}
