"use client";
import { useCallback,useEffect,useState } from "react";
import { AdminRangeFilter,RangePreset,formatChina,presetBounds,toRangeQuery } from "./AdminRangeFilter";

type Path={path:string;title?:string;visitedAt:string}; type Session={id:string;startedAt:string;lastSeenAt:string;country:string;source:string;medium?:string;campaign?:string;landingPage:string;pageCount:number;paths:Path[]}; type Lead={id:string;name:string;company:string;status:string;createdAt:string;source:string};
type Detail={profile:{anonymousId?:string;ipMasked?:string;sessionCount?:number;firstSeenAt?:string;lastSeenAt?:string;country?:string;firstSource?:string;latestSource?:string;firstLandingPage?:string;classification?:string};sessions:Session[];leads:Lead[]};
export function VisitorDetail({visitorId}:{visitorId:string}){const initial=presetBounds("month");const [preset,setPreset]=useState<RangePreset>("month"),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[data,setData]=useState<Detail|null>(null),[message,setMessage]=useState(""),[expanded,setExpanded]=useState<string|null>(null);
 function changePreset(next:RangePreset){setPreset(next);if(next!=="custom"){const b=presetBounds(next);setFrom(b.from);setTo(b.to);}}
 const load=useCallback(async()=>{const dates=toRangeQuery(from,to);const r=await fetch("/api/admin/visitors/"+visitorId+"?"+new URLSearchParams(dates),{cache:"no-store"}),j=await r.json();if(r.ok){setData(j.data);setMessage("");}else setMessage(j.message??"读取失败。");},[visitorId,from,to]);
 useEffect(()=>{void load();},[load]);const p=data?.profile;
 return <main className="admin-content admin-content-wide"><header className="admin-header"><div><p className="admin-kicker">VISITOR JOURNEY</p><h1>访问详情</h1><p className="admin-subtitle">同一访客的所有会话、页面顺序、来源与关联询盘。</p></div><a className="admin-logout" href="/admin/visitors">返回访客中心</a></header><AdminRangeFilter preset={preset} from={from} to={to} onPreset={changePreset} onFrom={setFrom} onTo={setTo} onApply={()=>void load()}/>
 {!data?<section className="admin-callout"><h2>{message||"正在读取访客轨迹…"}</h2></section>:<><section className="admin-profile-grid">{[["访客编号",p.anonymousId],["会话次数",String(p.sessionCount??0)],["国家 / 地区",p.country],["脱敏 IP",p.ipMasked],["首次来源",p.firstSource],["最近来源",p.latestSource],["首次访问",formatChina(p.firstSeenAt)],["最近访问",formatChina(p.lastSeenAt)]].map(([label,value])=><article key={label}><span>{label}</span><b>{value||"—"}</b></article>)}</section>
 <section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">SESSION TIMELINE</p><h2>全部访问路径</h2></div><span className="admin-hint">展开任意一次访问可查看页面进入顺序与渠道归因。</span></div>{data.sessions.length?data.sessions.map(s=><article className="admin-session" key={s.id}><button className="admin-session-head" onClick={()=>setExpanded(expanded===s.id?null:s.id)}><span><b>{formatChina(s.startedAt)}</b><small>{s.country} · {s.source} · {s.pageCount} 页</small></span><span>{expanded===s.id?"收起":"查看路径"}</span></button>{expanded===s.id&&<div className="admin-path-timeline"><p><b>落地页：</b>{s.landingPage}　<b>来源：</b>{s.source}{s.medium?" / "+s.medium:""}{s.campaign?" / "+s.campaign:""}</p>{s.paths.length?s.paths.map((path,index)=><div key={path.visitedAt+"-"+index}><span>{String(index+1).padStart(2,"0")}</span><b>{path.path}</b><small>{path.title||"页面浏览"} · {formatChina(path.visitedAt)}</small></div>):<p className="admin-hint">该会话没有可展示的页面事件。</p>}</div>}</article>):<p className="admin-empty">该时间范围没有有效访问记录。</p>}</section>
 <section className="admin-panel"><div className="admin-panel-heading"><div><p className="admin-kicker">LEAD ATTRIBUTION</p><h2>关联询盘</h2></div></div><div className="admin-table-scroll"><table><thead><tr><th>联系人</th><th>公司</th><th>来源</th><th>提交时间</th><th>状态</th></tr></thead><tbody>{data.leads.length?data.leads.map(l=><tr key={l.id}><td>{l.name}</td><td>{l.company}</td><td>{l.source}</td><td>{formatChina(l.createdAt)}</td><td><span className="admin-tag">{l.status}</span></td></tr>):<tr><td colSpan={5} className="admin-empty">此访客尚未产生关联询盘。</td></tr>}</tbody></table></div></section></>}</main>;}
