create or replace function public.admin_list_visitors(
  p_from timestamptz, p_to timestamptz, p_country text default null,
  p_source text default null, p_query text default null, p_page integer default 1,
  p_page_size integer default 20
) returns jsonb language sql stable security definer set search_path = '' as $$
with sessions as (select s.*, v.id as visitor_id from public.analytics_sessions s join public.analytics_visitors v on v.id = s.visitor_id where s.started_at between p_from and p_to and s.is_excluded = false and (p_country is null or s.country_code = upper(p_country)) and (p_source is null or lower(coalesce(s.source, 'direct')) = lower(p_source))), rows as (select s.visitor_id, coalesce(max(s.country_code), 'Unknown') as country, coalesce(max(s.source), 'Direct') as source, count(*)::int as sessions, coalesce(sum(s.page_count), 0)::int as page_views, max(s.last_seen_at) as last_seen, (array_agg(coalesce(s.landing_page, '/') order by s.started_at desc))[1] as latest_page from sessions s group by s.visitor_id), filtered as (select * from rows where p_query is null or country ilike '%' || p_query || '%' or source ilike '%' || p_query || '%' or latest_page ilike '%' || p_query || '%')
select jsonb_build_object('total', (select count(*) from filtered), 'items', coalesce((select jsonb_agg(jsonb_build_object('id', visitor_id, 'country', country, 'source', source, 'sessions', sessions, 'pageViews', page_views, 'lastSeen', to_char(last_seen at time zone 'UTC', 'YYYY-MM-DD HH24:MI'), 'latestPage', latest_page) order by last_seen desc, visitor_id) from (select * from filtered order by last_seen desc, visitor_id offset greatest((p_page-1)*least(greatest(p_page_size, 20),100),0) limit least(greatest(p_page_size,20),100)) x), '[]'::jsonb));
$$;
create or replace function public.admin_get_visitor_detail(p_visitor_id uuid) returns jsonb language sql stable security definer set search_path = '' as $$
select jsonb_build_object('visitor', (select jsonb_build_object('id', v.id, 'firstSeen', to_char(v.first_seen_at at time zone 'UTC','YYYY-MM-DD HH24:MI'), 'lastSeen', to_char(v.last_seen_at at time zone 'UTC','YYYY-MM-DD HH24:MI')) from public.analytics_visitors v where v.id=p_visitor_id), 'sessions', coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'startedAt',to_char(s.started_at at time zone 'UTC','YYYY-MM-DD HH24:MI'),'lastSeen',to_char(s.last_seen_at at time zone 'UTC','YYYY-MM-DD HH24:MI'),'country',coalesce(s.country_code,'Unknown'),'source',coalesce(s.source,'Direct'),'landingPage',coalesce(s.landing_page,'/'),'pageCount',s.page_count,'referrer',s.referrer,'campaign',s.campaign,'device',s.device_type) order by s.started_at desc) from public.analytics_sessions s where s.visitor_id=p_visitor_id and s.is_excluded=false), '[]'::jsonb), 'events', coalesce((select jsonb_agg(jsonb_build_object('at',to_char(e.created_at at time zone 'UTC','YYYY-MM-DD HH24:MI'),'type',e.event_name,'page',coalesce(e.page_path,'/'),'title',e.page_title) order by e.created_at desc) from (select e.* from public.analytics_events e where e.visitor_id=p_visitor_id and e.is_excluded=false order by e.created_at desc limit 250) e), '[]'::jsonb), 'leads', coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'name',l.name,'company',l.company,'status',l.status,'createdAt',to_char(l.created_at at time zone 'UTC','YYYY-MM-DD HH24:MI')) order by l.created_at desc) from public.leads l join public.analytics_visitors v on v.anonymous_id=l.anonymous_id where v.id=p_visitor_id), '[]'::jsonb));
$$;
revoke all on function public.admin_list_visitors(timestamptz,timestamptz,text,text,text,integer,integer) from public,anon,authenticated;
revoke all on function public.admin_get_visitor_detail(uuid) from public,anon,authenticated;
grant execute on function public.admin_list_visitors(timestamptz,timestamptz,text,text,text,integer,integer) to service_role;
grant execute on function public.admin_get_visitor_detail(uuid) to service_role;
