create or replace function public.admin_list_leads(p_from timestamptz, p_to timestamptz, p_status text default null, p_query text default null, p_page integer default 1, p_page_size integer default 20) returns jsonb language sql stable security definer set search_path = '' as $$
with filtered as (select l.* from public.leads l where l.created_at between p_from and p_to and (p_status is null or lower(l.status)=lower(p_status)) and (p_query is null or l.name ilike '%'||p_query||'%' or l.company ilike '%'||p_query||'%' or l.email ilike '%'||p_query||'%'))
select jsonb_build_object('total',(select count(*) from filtered),'items',coalesce((select jsonb_agg(jsonb_build_object('id',id,'name',name,'company',company,'email',email,'country',coalesce(country_name,country_code,'Unknown'),'application',application,'source',coalesce(source,'Direct'),'status',status,'createdAt',to_char(created_at at time zone 'UTC','YYYY-MM-DD HH24:MI'),'nextFollowUpAt',case when next_follow_up_at is null then null else to_char(next_follow_up_at at time zone 'UTC','YYYY-MM-DD HH24:MI') end) order by created_at desc,id desc) from (select * from filtered order by created_at desc,id desc offset greatest((p_page-1)*least(greatest(p_page_size,20),100),0) limit least(greatest(p_page_size,20),100)) x),'[]'::jsonb));
$$;
create or replace function public.admin_get_lead_detail(p_lead_id uuid) returns jsonb language sql stable security definer set search_path = '' as $$
select jsonb_build_object('lead',(select to_jsonb(l) - 'anonymous_id' || jsonb_build_object('id',l.id,'visitorId',v.id) from public.leads l left join public.analytics_visitors v on v.anonymous_id=l.anonymous_id where l.id=p_lead_id), 'notes',coalesce((select jsonb_agg(jsonb_build_object('id',n.id,'note',n.note,'stage',n.stage,'createdAt',to_char(n.created_at at time zone 'UTC','YYYY-MM-DD HH24:MI'),'nextFollowUpAt',case when n.next_follow_up_at is null then null else to_char(n.next_follow_up_at at time zone 'UTC','YYYY-MM-DD HH24:MI') end) order by n.created_at desc) from public.lead_notes n where n.lead_id=p_lead_id),'[]'::jsonb));
$$;
revoke all on function public.admin_list_leads(timestamptz,timestamptz,text,text,integer,integer) from public,anon,authenticated;
revoke all on function public.admin_get_lead_detail(uuid) from public,anon,authenticated;
grant execute on function public.admin_list_leads(timestamptz,timestamptz,text,text,integer,integer) to service_role;
grant execute on function public.admin_get_lead_detail(uuid) to service_role;
